# Generated by Django 5.0.dev20230727134847 on 2023-09-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['nombre'], 'verbose_name': 'Director', 'verbose_name_plural': 'Directores'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['nombre'], 'verbose_name': 'Genero', 'verbose_name_plural': 'Generos'},
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['ano'], 'verbose_name': 'Pelicula', 'verbose_name_plural': 'Peliculas'},
        ),
    ]
